### ISSUE TITLE
run couchdb as daemon

### ISSUE THREAD

**Issue by kentyler** [jhs/build-couchdb#16]
i have a ubuntu 10.4 box where i used build-couchdb to install couchdb... that works. now i want to start it as a daemon...preferrably every time the machine restarts

i seem to remember at one time the readme said using the -d flag would do that... but that just gives a "couchdb is not running" error on my machine

i see the build-couch folder has its own init.d folder...  but i'm pretty much at sea without further help

are there instructions for doing this after using build-couchdb... or a least  documentation of which user build-couch sets up to run couch 

i'm a little hesitant to just start changing things because i might mess up some sort of dependencies that build-couchdb will need 

thanks
ken tyler

**Comment by dflourusso** [comment]
Run as daemon: `couchdb -b`
See status: `couchdb -s`
Kill bg process: `couchdb -d`
