### ISSUE TITLE
CentOS 6.5 Building with Erlang R16B0x fails to start

### ISSUE THREAD

**Issue by dalgibbard** [jhs/build-couchdb#26]
Hi all,
It would seem that if you build CouchDB (tested version 1.4 and 1.6) against Erlang R16B0x (Tested B03 and B03-1) on CentOS 6.4 / 6.5 x86_64, the completed build fails to start, with the error featured in: http://erlang.org/pipermail/erlang-questions/2014-February/076760.html

To fix, add to tasks/erlang.rake:44 `“-DOPENSSL_NO_EC=1″`

**Comment by iknox** [comment]
This is a bit of an old issue but I found that adding 
```
erl_cflags="-DOPENSSL_NO_EC=1"
```
didn't seem to have any effect.  I just added it directly to the rake job with 
```
sed -i 's/#{cflags}/#{cflags} -DOPENSSL_NO_EC=1/g' tasks/erlang.rake
```

**Comment by dalgibbard** [comment]
Closing as this all referrers to old stuff :)
